---
- name: download rancher cli archive
  get_url: url=https://github.com/rancher/cli/releases/download/{{ rancher_cli_version }}/rancher-linux-amd64-{{ rancher_cli_version }}.tar.gz
           dest=/opt/rancher-linux-amd64-{{ rancher_cli_version }}.tar.gz
           force=no


- name: unpack rancher cli archive
  command: tar -xvzf rancher-linux-amd64-{{ rancher_cli_version }}.tar.gz chdir=/opt creates=/home/{{ user }}/rancher-{{ rancher_cli_version }}


- name: move rancher cli binary
  command: mv rancher /usr/bin/rancher chdir=/opt/rancher-{{ rancher_cli_version }} creates=/usr/bin/rancher


- name: remove rancher cli folder
  file: path=/opt/rancher-{{ rancher_cli_version }}
        state=absent


- name: remove rancher cli archive
  file: path=/opt/rancher-linux-amd64-{{ rancher_cli_version }}.tar.gz
        state=absent
